name: Tuğba Öztürk 
author: Tuğba Öztürk 
baseurl: https://thetugbashow.github.io
description: All things Tuğba
twitter: https://www.twitter.com/thetugbashow
youtube: https://www.youtube.com/channel/UCIIYzSMHOeRg8X6jAC9Mmbg
instagram: https://www.instagram.com/tugbashow/
email: av.ozturktugba@gmail.com
location: İzmir, Türkiye

highlighter: rouge

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
