name: Tuğba Öztürk
author: Tuğba Öztürk
baseurl: /thetugbashow
description: Personal website
# add LinkedIn, FaceBook?
twitter: https://www.twitter.com/thetugbashow
youtube: https://www.youtube.com/channel/UCIIYzSMHOeRg8X6jAC9Mmbg
instagram:
email: av.ozturktugba@gmail.com
location: İzmir, Türkiye

##Make sure to edit the above fields


highlighter: pygments
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
